init python:
  def Act02():
    renpy.say(p, "Act 2: A form of friendship.");
    renpy.say(p, "1. The kingdom was vast, yet, quite plain. It, like its citizens lacked color. In fact it only had one. It was monochromatic. Everything was so bland, so ‘typical.&#39; The environment, like of the people of Parchment was quite dull. Making the task at hand seem ever more daunting, but our Princess had resolve.");

    renpy.say(p, "2. Amongst the common folk there had to be one gem, one option. There were candidates that piqued her interest, but they were often odd, and a little disappointing despite low standards; One was a baker, another a bachelor, as well as a butcher, and even a scarecrow. rag tag, but she&#39;d just have to make due. Your options are your options. (None the less, you all really ought to audition.) (baker: audition?) (bachelor: what? ) (butcher: arrrrghhhh) (crow: ...) They were not aware that they had to audition. (&quot;well clearly these suitors aren&#39;t very suited to dine with me. And I refuse to settle. If they will not at least entertain me, then they have clearly wasted my time.) She stuck her nose up into the air and began walking away.");

    renpy.say(p, "3. But before she could walk away (&quot;Take me with you. Please take me with you?&quot;) (&quot;You want to come with me? I guess you recognize my glory&quot;) (&quot;Yes, yes, i do. I truly do. Now please take me with you my dear princess&quot;) (Well then, you may join me on my quest to find more people like me, on one condition. You must obey my every command. Since I am the princess after all. &quot;) (yes, without a doubt my glamorous princess) And thus began a beautiful yet unconditionally one-sided friendship. If you could call it that... (&quot;get over here bear&quot;) (&quot;what&quot;) And so she stuck him in her bag (I&#39;m not a bear I&#39;m a scarecrow that happens to look like a bear.) (just get in there) and she shoved the poor talking scarecrow into her bag (&quot;Oh my&quot;)");

    renpy.say(p, "4. Despite finding a new comrade, the Princess was far from completing her quest. After journeying to the edge of the Kingdom she realized that there were no royal colours to be found. Was there no one worthy enough to dine at her table? &quot;No, I can’t give up, there must be someone.&quot; That’s when she had a stroke of genius! &quot;I’ve got it&quot; She decided to climb up to the top of the Northern tower to see if she could spot someone.");

    renpy.say(p, "5. &quot;What a great idea&quot; but then out of nowhere fate intervened... &quot;oh my&quot; Or, well... The wind did. A gust of wind suddenly blew her crown off, and her crown flew away. (&quot;The wind, that bugger!! It’s stolen my crown&quot;) of course this event lead our Prince to the most rational possible conclusion. (&quot;The wind, it has become my enemy. It is attempting to sabotage my mission.&quot;) And so she began battling against the wind itself. Unfortunately that didn&#39;t go so well, and our paper protagonist was carried off by a gust of wind. Just like her paper crown was to who knows where.");