
init python:
  def Act04():
    renpy.say(p, "1. Where was she? Everything was a blur. For a moment the princess just sat in daze, starring at her reflection in a puddle. She was the same, but somehow different. Appearing rough and sketchy looking a lot like the people she had rejected. Was she no better than anyone else? &quot;But, If I&#39;m special... then why... Wait a moment, am I sitting in Sewage?&quot; She leaped to her feet only to slip back into the muck.");

    renpy.say(p, "2. &quot;I really do hate... Wait, what&#39;s that noise?&quot; There was chatter in the distance; she could make out two silhouettes. One handed the other something, hoped into a carriage left. The other, after receiving the package began walking in her direction, turning out to be the bear. “I’m a scarecrow” The princess then groaned &quot;where are we?&quot; “well... You see princess, I have always lived here, it is my home, as you.... have always lived through there.&quot; pulling a curtain, he revealed an odd entrance to the castle. &quot;Now, we must be careful princess, since of course, you lack a crown. Without it you will be seen no differently than a commoner. We must use our wits to… wait… where did she…”Unfortunately, she had already run off. &quot;Go..?”");

    renpy.say(p, " 3. Where was she, it was dark and the atmosphere felt heavy. Suddenly spotlights illuminated everything: “I’m in the court room? Everyone?” She looks up to see countless glazed over eyes locked to her. “Hey, it me everyone. The princess!)(&quot; What? rift raft like you, the princess? Haa ha ha. Don’t make me laugh.) (but… I…) a shadow loomed over her (are you trying to insult my intelligence.) (Who is she, who is she?) (The princess?) (No, no.) (Clearly an imposter.) (Look at her appearing in the real ones wake.) (See, no princess here. Just an imposter and we all know what we do to imposter’s correct..?) Silence filled the room; the people she once rejected were now judging her.");

    renpy.say(p, "4. “Oh, I hear someone coming. That must be the king. Unfortunately for you, he will decide your fate” The king stumbled in fidgeting with his glasses, and clearing his throat: “Hello everyone, how are you today?&quot; All at once the crowd responded: “good Mr. King&quot; &quot;well now, that&#39;s good to hear. Now who is this child?&quot; He adjusted his glasses as he leaned in to get a closer look. “Hm… Actually, before we address this issue, we have a much bigger problem... Why didn&#39;t any of you ask how my day was? Seems a little inconsiderate doesn’t it?” “With all due respect sir, that’s not the point. You see this person is an imposter. Just look at her all ripped and smeared pretending to be our princess” His words cut deep; it was as though it was all over. Clearly her father the king didn’t even recognize her.");

    renpy.say(p, "5. Are you just doing to give up? I guess without your fancy crown we&#39;re no different? No, even I don&#39;t give up that easily.&quot; Was that, Teddy? (&quot;Princess, you aren&#39;t a birth rite, or job, or even any of that other fancy stuff. You are you, and only you can only be you. And when you realize who you are, that is when you&#39;ll shine brighter than any silly crown. And king, you need to get your glasses checked since clearly… this is your daughter the princess. &quot;) It was Teddy, but oh no, that definitely wasn’t what he was supposed to say. Especially to the King.");

    renpy.say(p, "6. (Oh no he didn’t) (“I never…”) The crowd began to swarm around him, ready to pounce. &quot;Father stop them!&quot; &quot;What are you doing Henry&quot; &quot;divine retribution sir?&quot; &quot;Devine what? What are you even talking… ugh, never mind that’s not the point. Now Henry do you recognize who that little girl is, right?&quot; &quot;An imposter?&quot; &quot;Well, clearly you can’t see the resemblance. A father can always recognize his daughter. Can’t any of you see the resemblance?” Henry looked terrified, fortunately the crowd was there to surmise the situation “Ooo… awkward.” &quot;Now princess, there is something you have very much in Common with these people. Always judge everyone and everything.” “sorry” “Though I’m glad you’re finally home&quot; &quot;cough. Cough. Hurray she’s home!&quot; The Prince was happy to be back, but something wasn&#39;t right. Everything was as it should be though; there was one last thing she had to do: “Everyone, Please listen. I no longer want anyone to address me by my title, I&#39;m more than just a title. I&#39;m a person, and my name is Sarah, Sarah Mont Flawle the 5th.”");

    renpy.say(p, "7. Unfortunately no one was paying attention to her &quot;is he devine!” “No he&#39;s the new king!&quot; The princess and her father were awestruck: “what?” If you all recall correctly there is one symbol of royalty in this world colour, even though he&#39;s just a bear, he still has that mask. You remember the one? Right? Yep, that one. &quot;This bear, he is royalty, perhaps even greater than the king himself.&quot; &quot;teddy?&quot; “Hey I tried to tell you to use your wits.”");

    renpy.say(p, "8. Fortunately Teddy had no interest in becoming king. Instead he decided become Parchments first Devine Overseer. And for his first act, he decided to throw a big feast with everyone in the kingdom, both colourful and colourless alike. Everyone was welcome. And of course, they all lived happily ever after. After all, what else would they do?");

    renpy.say(p, "9. -There&#39;s one last detail, the crown did finally make its way back to the princess. (Princess looks at the crown). I think he made the right choice (throws away the crown) -the end");

    renpy.say(p, "All paths lead here. Yes, they diverge and zag, but they all lead to this end.");



